// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv3I2hxLM2_g4tQuvWKg6yVwJ_fXIfswE',
    appId: '1:747894783578:web:77a87c7e713fe54b3c2263',
    messagingSenderId: '747894783578',
    projectId: 'mic-whispers-7d061',
    authDomain: 'mic-whispers-7d061.firebaseapp.com',
    storageBucket: 'mic-whispers-7d061.firebasestorage.app',
    measurementId: 'G-E5P9HNH2VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOWB_N5WJK7Ugs649xcFWwlOW65B-Xbc',
    appId: '1:747894783578:android:78f5d23d47ede6b93c2263',
    messagingSenderId: '747894783578',
    projectId: 'mic-whispers-7d061',
    storageBucket: 'mic-whispers-7d061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3uBuOxVpVwjQ_D7WSmDZ08SHZm9uwwwA',
    appId: '1:747894783578:ios:6d32fc1a9c9598d53c2263',
    messagingSenderId: '747894783578',
    projectId: 'mic-whispers-7d061',
    storageBucket: 'mic-whispers-7d061.firebasestorage.app',
    iosBundleId: 'com.wellnoc.micwhispers.micWhispers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3uBuOxVpVwjQ_D7WSmDZ08SHZm9uwwwA',
    appId: '1:747894783578:ios:6d32fc1a9c9598d53c2263',
    messagingSenderId: '747894783578',
    projectId: 'mic-whispers-7d061',
    storageBucket: 'mic-whispers-7d061.firebasestorage.app',
    iosBundleId: 'com.wellnoc.micwhispers.micWhispers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv3I2hxLM2_g4tQuvWKg6yVwJ_fXIfswE',
    appId: '1:747894783578:web:cec6b4a76f66f3ee3c2263',
    messagingSenderId: '747894783578',
    projectId: 'mic-whispers-7d061',
    authDomain: 'mic-whispers-7d061.firebaseapp.com',
    storageBucket: 'mic-whispers-7d061.firebasestorage.app',
    measurementId: 'G-DXM44MB8LJ',
  );
}
